# Preprocessing the Data for a Neural Network

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
import pandas as pd 

# Import and read the charity_data.csv.
rawDF = pd.read_csv("Dataset for Use.csv")
rawDF.head()

C:\Users\dia78039\Anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (24,26,29,31,34,41,43,45,48,49,51) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,brand,spend,campaign_id,account_id,campaign_name,status,mapped_storeid,end_advertiser,business_manager_manager_id,end_advertiser_name,...,Support Regions,maturity,open_date,market,tier,ownership_group,soft_open_status,campaign_status,manager_customer_id,serving_status
0,B1,536.29,1.700630e+09,5.144417e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SERVING
1,B1,253.35,1.715917e+09,5.144417e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SERVING
2,B1,125.22,1.441660e+10,5.144417e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAUSED,2.076624e+09,SERVING
3,B1,289.04,1.700630e+09,5.144417e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SERVING
4,B1,322.95,1.715917e+09,5.144417e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SERVING

In [7]:
rawDF.info()
# columns to drop from index match: 
# 4, 8, 9, 10, 13, 20, 21, 22, 23, 25, 26, 27, 30, 32, 36, 37, 38, 42, 50

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203965 entries, 0 to 203964
Data columns (total 52 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   brand                        168645 non-null  object
 1   spend                        203965 non-null  float64
 2   campaign_id                  203965 non-null  float64
 3   account_id                   203965 non-null  float64
 4   campaign_name                0 non-null       float64
 5   status                       196414 non-null  object
 6   mapped_storeid               202123 non-null  float64
 7   end_advertiser               195943 non-null  float64
 8   business_manager_manager_id  196414 non-null  float64
 9   end_advertiser_name          195943 non-null  object
 10  business_manager_name        196414 non-null  object
 11  platform                     203965 non-null  object
 12  map_status                   203965 non-null  object
 13  api campaign id              196414 non-null  float64
 14  date_start                   203965 non-null  object
 15  impressions                  203965 non-null  int64
 16  leads                        200328 non-null  float64
 17  website_leads                196414 non-null  float64
 18  link_clicks                  203965 non-null  int64
 19  reach                        196414 non-null  float64
 20  version_id                   41489 non-null   float64
 21  connection_id                41489 non-null   float64
 22  brand_id                     41489 non-null   float64
 23  studio_service_id            41489 non-null   float64
 24  status_date                  41489 non-null   object
 25  agency_id                    41489 non-null   float64
 26  agency_name                  41489 non-null   object
 27  clubready_referraltypeid     203965 non-null  int64
 28  referraltypeid               41489 non-null   float64
 29  name                         47178 non-null   object
 30  chainid                      47178 non-null   float64
 31  country                      47178 non-null   object
 32  is_cap                       47178 non-null   float64
 33  agency                       203965 non-null  object
 34  channel                      41489 non-null   object
 35  type                         203964 non-null  object
 36  store_id                     201091 non-null  float64
 37  chain_id                     201911 non-null  float64
 38  chain_name                   201911 non-null  object
 39  location_name                201911 non-null  object
 40  state                        201421 non-null  object
 41  open_status                  106508 non-null  object
 42  Support Regions              0 non-null       float64
 43  maturity                     106575 non-null  object
 44  open_date                    168929 non-null  object
 45  market                       39970 non-null   object
 46  tier                         87459 non-null   float64
 47  ownership_group              14076 non-null   object
 48  soft_open_status             106575 non-null  object
 49  campaign_status              7551 non-null    object
 50  manager_customer_id          7551 non-null    float64
 51  serving_status               7551 non-null    object
dtypes: float64(24), int64(3), object(25)
memory usage: 80.9+ MB

In [3]:
# for loop to count understand what values are in "brand" column

# variable to hold the count
cnt = 0
  
# list to hold my B3 values
b3Vals = []
  
# loop for counting the unique
# values in height
for i in range(0, len(rawDF['brand'])):
    
    if rawDF['brand'][i] not in b3Vals: 
    
        b3Vals.append(rawDF['brand'][i])
          
        cnt += 1
  
print("No.of.unique values :",
      cnt)
  
print("unique values name :",
      b3Vals)

No.of.unique values : 3
unique values name : ['B1', 'B2', 'B3']

In [4]:
# First objective; drop all "B3" rows within column "brand"

# observe column brand
rawDF.loc[rawDF['brand']== 'B3']
# output shows B3 starts (index) at 168645 and ends at 203964

,brand,spend,campaign_id,account_id,campaign_name,status,mapped_storeid,end_advertiser,business_manager_manager_id,end_advertiser_name,...,Support Regions,maturity,open_date,market,tier,ownership_group,soft_open_status,campaign_status,manager_customer_id,serving_status
168645,B3,211.23,9.579951e+09,9.610313e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SUSPENDED
168646,B3,276.39,9.579951e+09,9.610313e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SUSPENDED
168647,B3,4.00,1.440085e+10,9.610313e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAUSED,2.076624e+09,SUSPENDED
168648,B3,411.61,1.010744e+10,9.610313e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SUSPENDED
168649,B3,79.15,9.579951e+09,9.610313e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,2.076624e+09,SUSPENDED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203960,B3,77.28,2.380000e+16,1.670000e+15,NaN,PAUSED,11204.0,1.180000e+14,1.180000e+14,Agency 3,...,NaN,NaN,5/29/2021,NaN,3.0,NaN,NaN,NaN,NaN,NaN
203961,B3,11.49,2.380000e+16,9.940000e+14,NaN,PAUSED,9376.0,1.180000e+14,1.180000e+14,Agency 3,...,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN,NaN
203962,B3,18.03,2.380000e+16,9.940000e+14,NaN,PAUSED,9376.0,1.180000e+14,1.180000e+14,Agency 3,...,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN,NaN
203963,B3,17.27,2.380000e+16,9.940000e+14,NaN,PAUSED,9376.0,1.180000e+14,1.180000e+14,Agency 3,...,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN,NaN
203964,B3,11.81,2.380000e+16,9.940000e+14,NaN,PAUSED,9376.0,1.180000e+14,1.180000e+14,Agency 3,...,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Drop all B3 values from brand column:
rawDF['brand'] = rawDF['brand'].drop(labels=range(168645, 203965), axis=0)

In [6]:
# check if any B3 values remain
rawDF.loc[rawDF['brand']== 'B3']

Empty DataFrame
Columns: [brand, spend, campaign_id, account_id, campaign_name, status, mapped_storeid, end_advertiser, business_manager_manager_id, end_advertiser_name, business_manager_name, platform, map_status, api campaign id, date_start, impressions, leads, website_leads, link_clicks, reach, version_id, connection_id, brand_id, studio_service_id, status_date, agency_id, agency_name, clubready_referraltypeid, referraltypeid, name, chainid, country, is_cap, agency, channel, type, store_id, chain_id, chain_name, location_name, state, open_status, Support Regions, maturity, open_date, market, tier, ownership_group, soft_open_status, campaign_status, manager_customer_id, serving_status]
Index: []

[0 rows x 52 columns]

In [11]:
# filtered out B3, now.. 
# DROP predetermined Nan or confidential columns to remove by index: 
# 4, 8, 9, 10, 13, 20, 21, 22, 23, 25, 26, 27, 30, 32, 36, 37, 38, 42, 50 
cleanDf = rawDF.drop(rawDF.columns[[4,8, 9, 10, 13, 20, 21, 22, 23, 25, 26, 27, 30, 32, 36, 37, 38, 42, 50]], axis=1)
cleanDf

,brand,spend,campaign_id,account_id,status,mapped_storeid,end_advertiser,platform,map_status,date_start,...,state,open_status,maturity,open_date,market,tier,ownership_group,soft_open_status,campaign_status,serving_status
0,B1,536.29,1.700630e+09,5.144417e+09,NaN,NaN,NaN,Google Ads,manual,12/13/2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,SERVING
1,B1,253.35,1.715917e+09,5.144417e+09,NaN,NaN,NaN,Google Ads,manual,3/20/2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,SERVING
2,B1,125.22,1.441660e+10,5.144417e+09,NaN,NaN,NaN,Google Ads,manual,8/28/2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAUSED,SERVING
3,B1,289.04,1.700630e+09,5.144417e+09,NaN,NaN,NaN,Google Ads,manual,7/13/2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,SERVING
4,B1,322.95,1.715917e+09,5.144417e+09,NaN,NaN,NaN,Google Ads,manual,4/10/2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENABLED,SERVING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203960,NaN,77.28,2.380000e+16,1.670000e+15,PAUSED,11204.0,1.180000e+14,Facebook Ads,auto,6/29/2021,...,CA,NaN,NaN,5/29/2021,NaN,3.0,NaN,NaN,NaN,NaN
203961,NaN,11.49,2.380000e+16,9.940000e+14,PAUSED,9376.0,1.180000e+14,Facebook Ads,auto,6/28/2021,...,CA,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN
203962,NaN,18.03,2.380000e+16,9.940000e+14,PAUSED,9376.0,1.180000e+14,Facebook Ads,auto,6/27/2021,...,CA,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN
203963,NaN,17.27,2.380000e+16,9.940000e+14,PAUSED,9376.0,1.180000e+14,Facebook Ads,auto,6/26/2021,...,CA,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN
203964,NaN,11.81,2.380000e+16,9.940000e+14,PAUSED,9376.0,1.180000e+14,Facebook Ads,auto,6/25/2021,...,CA,NaN,NaN,9/16/2020,NaN,5.0,NaN,NaN,NaN,NaN

In [15]:
# export clean CSV, for reference beore binning process
cleanDf.to_csv('cleanDf.csv')

# Rough/Quick Preprocessing Complete

# Binning

In [14]:
# # Determine the number of unique values in each column.
cleanDf.nunique()

brand                   2
spend               11108
campaign_id            83
account_id            469
status                  4
mapped_storeid        479
end_advertiser         46
platform                4
map_status              2
date_start            365
impressions          6336
leads                  74
website_leads          95
link_clicks           392
reach                5892
status_date           191
referraltypeid         15
name                   12
country                 2
agency                 12
channel                 1
type                    2
location_name         478
state                  46
open_status             2
maturity                1
open_date             255
market                 44
tier                    7
ownership_group         2
soft_open_status      179
campaign_status         3
serving_status          3
dtype: int64

# Split into train and test features

# Compile, Train, Evaluate our Model